// <auto-generated />
using System;
using CyberCafe.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CyberCafe.Api.Data.Migrations
{
    [DbContext(typeof(CyberCafeDbContext))]
    partial class CyberCafeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CyberCafe.Domain.Discounts.Discount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OrderDiscounts", (string)null);

                    b.HasDiscriminator<string>("DiscountType").HasValue("basic");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CyberCafe.Domain.Orders.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DiscountId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("PaymentId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DiscountId")
                        .IsUnique()
                        .HasFilter("[DiscountId] IS NOT NULL");

                    b.HasIndex("PaymentId")
                        .IsUnique()
                        .HasFilter("[PaymentId] IS NOT NULL");

                    b.HasIndex("Status");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("CyberCafe.Domain.Orders.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("CyberCafe.Domain.Payments.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.ToTable("Payments", (string)null);

                    b.HasDiscriminator<string>("PaymentType").HasValue("Payment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CyberCafe.Domain.Products.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Emoji")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("Products", (string)null);

                    b.HasDiscriminator<string>("ProductType").HasValue("product");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CyberCafe.Domain.Discounts.MemberDiscount", b =>
                {
                    b.HasBaseType("CyberCafe.Domain.Discounts.Discount");

                    b.Property<decimal>("Percent")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasDiscriminator().HasValue("member");
                });

            modelBuilder.Entity("CyberCafe.Domain.Discounts.VoucherDiscount", b =>
                {
                    b.HasBaseType("CyberCafe.Domain.Discounts.Discount");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("voucher");
                });

            modelBuilder.Entity("CyberCafe.Domain.Payments.CardPayment", b =>
                {
                    b.HasBaseType("CyberCafe.Domain.Payments.Payment");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CardNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasDiscriminator().HasValue("card");
                });

            modelBuilder.Entity("CyberCafe.Domain.Payments.CashPayment", b =>
                {
                    b.HasBaseType("CyberCafe.Domain.Payments.Payment");

                    b.Property<decimal>("CashReceived")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("cash");
                });

            modelBuilder.Entity("CyberCafe.Domain.Payments.MomoPayment", b =>
                {
                    b.HasBaseType("CyberCafe.Domain.Payments.Payment");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)")
                        .HasColumnName("MomoPhone");

                    b.HasDiscriminator().HasValue("momo");
                });

            modelBuilder.Entity("CyberCafe.Domain.Products.Cake", b =>
                {
                    b.HasBaseType("CyberCafe.Domain.Products.Product");

                    b.Property<string>("Flavor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("cake");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Description = "Vị cà phê, cacao",
                            Emoji = "🍰",
                            IsAvailable = true,
                            Name = "Bánh tiramisu",
                            Price = 35000m,
                            Flavor = "Cà phê"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Bơ Pháp, nướng mỗi sáng",
                            Emoji = "🥐",
                            IsAvailable = true,
                            Name = "Croissant bơ",
                            Price = 25000m,
                            Flavor = "Bơ"
                        });
                });

            modelBuilder.Entity("CyberCafe.Domain.Products.Coffee", b =>
                {
                    b.HasBaseType("CyberCafe.Domain.Products.Product");

                    b.Property<string>("BeanType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("coffee");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Robusta Đắk Lắk + sữa đặc",
                            Emoji = "☕",
                            IsAvailable = true,
                            Name = "Cà phê sữa đá",
                            Price = 29000m,
                            BeanType = "Robusta"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Nhiều sữa, ít cà phê",
                            Emoji = "🥛",
                            IsAvailable = true,
                            Name = "Bạc xỉu",
                            Price = 32000m,
                            BeanType = "Robusta"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Espresso pha loãng",
                            Emoji = "☕",
                            IsAvailable = true,
                            Name = "Americano",
                            Price = 35000m,
                            BeanType = "Arabica"
                        });
                });

            modelBuilder.Entity("CyberCafe.Domain.Products.Tea", b =>
                {
                    b.HasBaseType("CyberCafe.Domain.Products.Product");

                    b.Property<string>("TeaType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasDiscriminator().HasValue("tea");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            Description = "Trà đen, đào miếng, cam, sả",
                            Emoji = "🍑",
                            IsAvailable = true,
                            Name = "Trà đào cam sả",
                            Price = 39000m,
                            TeaType = "Trà đen"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Trà ô long, hạt sen, kem sữa",
                            Emoji = "🪷",
                            IsAvailable = true,
                            Name = "Trà sen vàng",
                            Price = 42000m,
                            TeaType = "Ô long"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Matcha Nhật + sữa tươi",
                            Emoji = "🍵",
                            IsAvailable = false,
                            Name = "Matcha latte",
                            Price = 45000m,
                            TeaType = "Matcha"
                        });
                });

            modelBuilder.Entity("CyberCafe.Domain.Orders.Order", b =>
                {
                    b.HasOne("CyberCafe.Domain.Discounts.Discount", "Discount")
                        .WithOne()
                        .HasForeignKey("CyberCafe.Domain.Orders.Order", "DiscountId");

                    b.HasOne("CyberCafe.Domain.Payments.Payment", "Payment")
                        .WithOne()
                        .HasForeignKey("CyberCafe.Domain.Orders.Order", "PaymentId");

                    b.OwnsOne("CyberCafe.Domain.People.Customer", "Customer", b1 =>
                        {
                            b1.Property<int>("OrderId")
                                .HasColumnType("int");

                            b1.Property<string>("FullName")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("CustomerName");

                            b1.Property<int>("LoyaltyPoints")
                                .HasColumnType("int")
                                .HasColumnName("CustomerLoyaltyPoints");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("nvarchar(11)")
                                .HasColumnName("CustomerPhone");

                            b1.HasKey("OrderId");

                            b1.ToTable("Orders");

                            b1.WithOwner()
                                .HasForeignKey("OrderId");
                        });

                    b.Navigation("Customer")
                        .IsRequired();

                    b.Navigation("Discount");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("CyberCafe.Domain.Orders.OrderItem", b =>
                {
                    b.HasOne("CyberCafe.Domain.Orders.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CyberCafe.Domain.Products.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("CyberCafe.Domain.Orders.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
